name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: "vfeeg-web"
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Setup
      run: npm install
    - name: Compile 
      run: npm run build
    - name: Set current version string
      run: echo "IMAGE_VERSION=latest-$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV      
    - name: Build the Docker image
      run: echo `docker build . --file Dockerfile --tag "ghcr.io/vfeeg-development/$IMAGE_NAME:$IMAGE_VERSION"`
    - name: Upload
      run: echo "docker push ghcr.io/vfeeg-development/$IMAGE_NAME:$IMAGE_VERSION"
