name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile 
      run: npm run build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/vfeeg-development/vfeeg-web:$(date +%s)
